### ISSUE TITLE
no motion blur for particles, shadows cast from wrong direction, instance object crash.

### ISSUE THREAD

**Issue by sloppyjava** [bsavery/PRMan-for-Blender#144]
![broke](https://cloud.githubusercontent.com/assets/8016352/10254074/0fc01186-6907-11e5-8062-c225c934e19f.jpg)

this illustrates the problem. after seeing a render of blobby particle type with motion blur i tried to duplicate and encountered these issues.  the particles are moving at approximately the same speed as the cube. 

Also illustrated in this scene, the sun's shadows are being cast from what appears to me to be a -180 Z rotation in relation to the light in the scene.

and finally, if i select object as the particle type blender throws an error and will exit without any warnings upon next render attempt.  the error is as follows:

'
Info: Texture generation took 00:00:00
Error: Rib gen error: Traceback (most recent call last):
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\engine.py", line 112, in update
    engine.render_pass.gen_rib(engine=engine)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\engine.py", line 540, in gen_rib
    write_rib(self, self.scene, self.ri)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 2351, in write_rib
    export_data_archives(ri, scene, rpass, data_blocks)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 1669, in export_data_
archives
    export_particle_archive(ri, scene, db)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 1808, in export_parti
cle_archive
    export_particle_system(ri, scene, ob, psys, data=data)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 1318, in export_parti
cle_system
    export_particles(ri, scene, ob, psys, data)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 906, in export_partic
les
    ri, scene, psys, ob, points, type=rm.particle_type)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 834, in export_partic
le_instances
    relative=True)
  File "C:\Users\hunter\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\PRMan-for-Blender-master\export.py", line 1711, in get_archive_
filename
    path = rpass.paths['frame_archives'] if animated \
AttributeError: 'NoneType' object has no attribute 'paths'

Info: PRMan: Done Rendering. (elapsed time: 00:00:00)
'

I hope these are easily sorted out.
Thanks again for the Killer Addon!

**Comment by bsavery** [comment]
Can you attach that scene?

**Comment by sloppyjava** [comment]
I had to re-create the problem scene. unfortunately, it seems i can only attach image files here so I uploaded it to dropbox.  

https://www.dropbox.com/s/do9y6d8pyjm7kfi/issue.blend?dl=0

I was unable to reproduce the reversed light direction this time, but i'll have another look later tonight.

**Comment by bsavery** [comment]
I fixed the crash.  Not sure whats going on with the MB though.... there's no anim data on the plane emitter or the psys.

**Comment by bsavery** [comment]
Should be fixed.
