### ISSUE TITLE
Bug: dupligroups, probably nullpointer

### ISSUE THREAD

**Issue by tobbew79** [bsavery/PRMan-for-Blender#175]
probably nullpointer if object set to duplication as dupligroups, but group field is empty:

Read new prefs: C:\Users\tobbew\AppData\Roaming\Blender Foundation\Blender\2.76\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.76\python
addon not found: 'mesh_discombobulator'
read blend: D:\blender\renderman_mb_deform_duplication.blend
ERROR:  ('Export path [C:\\Users\\tobbew\\My Documents\\prman_for_blender\\renderman_mb_deform_duplication\\images\\Scene_0008.exr] does not exist.',)
Info: Texture generation took 00:00:00
Error: Rib gen error: Traceback (most recent call last):
  File "D:\blender\git\addons\PRMan-for-Blender\engine.py", line 112, in update
    engine.render_pass.gen_rib(engine=engine)
  File "D:\blender\git\addons\PRMan-for-Blender\engine.py", line 541, in gen_rib
    write_rib(self, self.scene, self.ri)
  File "D:\blender\git\addons\PRMan-for-Blender\export.py", line 2575, in write_rib
    data_blocks, instances = cache_motion(scene, rpass)
  File "D:\blender\git\addons\PRMan-for-Blender\export.py", line 1780, in cache_motion
    get_instances_and_blocks(scene.objects, rpass)
  File "D:\blender\git\addons\PRMan-for-Blender\export.py", line 1607, in get_instances_and_blocks
    inst_data_blocks = get_data_blocks_needed(ob, rpass, mb_on)
  File "D:\blender\git\addons\PRMan-for-Blender\export.py", line 1700, in get_data_blocks_needed
    for dupli_ob in ob.dupli_group.objects:
AttributeError: 'NoneType' object has no attribute 'objects'

Error: PRMan: Exited

**Comment by bsavery** [comment]
Fixed in next checkin
