### ISSUE TITLE
IPR state got stucked when camera is on a hidden layer

### ISSUE THREAD

**Issue by nuzzar** [bsavery/PRMan-for-Blender#274]
I think I found a bug. When you start an IPR render and the camera is on a hidden layer blender outputs some error and the button got stucked in a ("Stop IPR") state even though the prman process itself has already been killed. Clicking the IPR button to stop the process would only give a different error. The only way to fix the IPR state is to restart blender.

The error output when you clicked the first time:

```
Traceback (most recent call last):
  File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/operators.py", line 306, in invoke
    engine.ipr.start_interactive()
  File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/engine.py", line 540, in start_interactive
    write_rib(self, self.scene, self.ri, visible_objects)
  File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/export.py", line 2900, in write_rib
    export_camera(ri, scene, instances)
  File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/export.py", line 2383, in export_camera
    i = instances[scene.camera.name]
KeyError: 'Camera'

location: <unknown location>:-1

location: <unknown location>:-1
```

```
The error output when you clicked the second time:

Traceback (most recent call last):
  File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/operators.py", line 314, in invoke
    engine.ipr_handle, 'WINDOW')
AttributeError: module 'PRMan-for-Blender.engine' has no attribute 'ipr_handle'

location: <unknown location>:-1

location: <unknown location>:-1
```

OS: Ubuntu 16.04
Branch: devel 4cc9aa4978a77f646aa443972c708f50429a3453

**Comment by bsavery** [comment]
Ok. I think should be easily fixable. I saw something similar recently.
Thanks!

On Saturday, June 4, 2016, nuzzar <notifications@github.com> wrote:

> I think I found a bug. When you start an IPR render and the camera is on a
> hidden layer blender outputs some error and the button got stucked in a
> ("Stop IPR") state even though the prman process itself has already been
> killed. Clicking the IPR button only give another error. The only way to
> fix the IPR state is to restart blender.
>
> The error output when you clicked the first time:
>
> Traceback (most recent call last):
>   File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/operators.py", line 306, in invoke
>     engine.ipr.start_interactive()
>   File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/engine.py", line 540, in start_interactive
>     write_rib(self, self.scene, self.ri, visible_objects)
>   File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/export.py", line 2900, in write_rib
>     export_camera(ri, scene, instances)
>   File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/export.py", line 2383, in export_camera
>     i = instances[scene.camera.name]
> KeyError: 'Camera'
>
> location: <unknown location>:-1
>
> location: <unknown location>:-1
>
> The error output when you clicked the second time:
>
> Traceback (most recent call last):
>   File "/home/log/.config/blender/2.77/scripts/addons/PRMan-for-Blender/operators.py", line 314, in invoke
>     engine.ipr_handle, 'WINDOW')
> AttributeError: module 'PRMan-for-Blender.engine' has no attribute 'ipr_handle'
>
> location: <unknown location>:-1
>
> location: <unknown location>:-1
>
> OS: Ubuntu 16.04
> Branch: devel 4cc9aa4
> <https://github.com/bsavery/PRMan-for-Blender/commit/4cc9aa4978a77f646aa443972c708f50429a3453>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/274>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABzffJepcRtr3Oh0Qn4uVBu2oCX9uZ6-ks5qIfhtgaJpZM4IuOxF>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
This should be fixes a while ago I think?

**Comment by MWY3510** [comment]
This is fixed as far as the master branch is concerned. Closing this because of no activity.
