### ISSUE TITLE
Some Dev-21 issues

### ISSUE THREAD

**Issue by jdent02** [bsavery/PRMan-for-Blender#329]
Tried to use PxrLayerSurface with one PxrLayer that had glass lobe enabled:

PRMan: S20002 {ERROR}   Could not open OSL shader PxrLayer (File "PxrLayer" could not be found.).

 
PRMan: R10041 {WARNING} Invalid or mismatched reference parameter "PxrLayer:pxrMaterialOut_glassIor" was found for input "glassIor" of instance "Material.PxrLayerSurface" of plugin "PxrLayerSurface" on gprim "refraction_sphere".

 
PRMan: R10041 {WARNING} Invalid or mismatched reference parameter "PxrLayer:pxrMaterialOut_glassRoughness" was found for input "glassRoughness" of instance "Material.PxrLayerSurface" of plugin "PxrLayerSurface" on gprim "refraction_sphere".

 
PRMan: R10041 {WARNING} Invalid or mismatched reference parameter "PxrLayer:pxrMaterialOut" was found for input "inputMaterial" of instance "Material.PxrLayerSurface" of plugin "PxrLayerSurface" on gprim "refraction_sphere".

 
PRMan: R10041 {WARNING} Invalid or mismatched reference parameter "PxrLayer:pxrMaterialOut_reflectionGain" was found for input "reflectionGain" of instance "Material.PxrLayerSurface" of plugin "PxrLayerSurface" on gprim "refraction_sphere".

 
PRMan: R10041 {WARNING} Invalid or mismatched reference parameter "PxrLayer:pxrMaterialOut_refractionColor" was found for input "refractionColor" of instance "Material.PxrLayerSurface" of plugin "PxrLayerSurface" on gprim "refraction_sphere".

 
PRMan: R10041 {WARNING} Invalid or mismatched reference parameter "PxrLayer:pxrMaterialOut_refractionGain" was found for input "refractionGain" of instance "Material.PxrLayerSurface" of plugin "PxrLayerSurface" on gprim "refraction_sphere".

**Comment by jdent02** [comment]
Also this one when I attempt to open some dropdowns in the node trees.  Specifically the "trace control" in subsurface and the "interior" in glass.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-devel-21\nodes.py", line 261, in draw_buttons
    self.draw_nonconnectable_props(context, layout, self.prop_names)
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-devel-21\nodes.py", line 309, in draw_nonconnectable_props
    context, layout, prop)
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-devel-21\nodes.py", line 309, in draw_nonconnectable_props
    context, layout, prop)
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\addons\PRMan-for-Blender-devel-21\nodes.py", line 290, in draw_nonconnectable_props
    prop_meta = self.prop_meta[prop_name]
TypeError: unhashable type: 'dict'

location: <unknown location>:-1

**Comment by jdent02** [comment]
![image](https://cloud.githubusercontent.com/assets/13521172/17279345/099f7052-5737-11e6-916c-95016b983895.png)

Seems like anytime I see a dropdown tree like this, trying to open the second error will trigger the second error.  First error was generated when I rendered.
