### ISSUE TITLE
PRMan activation impossible (error)

### ISSUE THREAD

**Issue by iyenal** [bsavery/PRMan-for-Blender#359]
Hello,
I'm trying to activate PRMan render engine addon, but when I click on the check box, Blender throw 2 errors :

`
Traceback (most recent call last):
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\scripts\modules\addon_utils.py", line 349, in enable
    mod.register()
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\scripts\addons\PRMan-for-Blender-master__init__.py", line 100, in register
    nodes.register()
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\scripts\addons\PRMan-for-Blender-master\nodes.py", line 1421, in register
    generate_node_type(prefs, name, ET.parse(arg_file).getroot())
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\python\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\python\lib\xml\etree\ElementTree.py", line 594, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

Traceback (most recent call last):
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\scripts\modules\addon_utils.py", line 349, in enable
    mod.register()
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\scripts\addons\PRMan-for-Blender-master__init__.py", line 89, in register
    preferences.register()
  File "C:\Users\travail\Downloads\blender-2.78-windows64\2.78\scripts\addons\PRMan-for-Blender-master\preferences.py", line 218, in register
    bpy.utils.register_class(RendermanPreferencePath)
ValueError: register_class(...): already registered as a subclass
`
I have reinstalled 3 times Renderman (with Maya 2014 plugin), 2 times Blender 2.78, 3 times this addon, but always this error.
Configuration : Intel Core i5 4e generation + Nvidia Geforce GTX 720M. All the drivers are out of date.
Thanks.

**Comment by MWY3510** [comment]
Good day, are you still experiencing this issue?

**Comment by MWY3510** [comment]
Ok, having heard no response I am going to close this issue. If you are still experiencing problems with the latest release go ahead and reopen this.

**Comment by iyenal** [comment]
No don't close the issue, or declose, I am still experiencing the issue, and I don't saw your messages, sorry, since I verify them only in the Renderman forum thread : https://renderman.pixar.com/forum/showthread.php?s=&threadid=32812
